on:
  pull_request:
  push:
    branches: main

name: Build and Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm test

  # check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Set up NPM
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18

  #     - run: npm ci

  #     - run: npm run build

  #     - run: npm run check-format

  #     - run: npm run lint

  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Set up NPM
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18

  #     - run: npm ci

  #     - run: npm run docs

  #     - uses: actions/upload-pages-artifact
  #       with:
  #         path: "docs"

  # deploy:
  #   # Add a dependency to the build job
  #   needs: docs

  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source

  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-latest

  #   steps:
  #     - id: deployment
  #       uses: actions/deploy-pages@v2